application: tracksonamap
version: dev
runtime: python
api_version: 1

handlers:
- url: /scripts
  static_dir: scripts  

- url: /style
  static_dir: style  
         
- url: /backend-update/track
  script: backend/update_track.py
  login: admin

- url: /backend-update-task
  script: backend/update_task.py
  login: admin

- url: /backend-update
  script: backend/update.py
  login: admin

- url: /backend-cleanup/.*
  script: backend/cleanup.py
  login: admin

- url: /backend-refill-memcache
  script: backend/refill_memcache.py
  login: admin

- url: /soundcloud-connect-auth.*
  script: soundcloud_connect_auth.py

- url: /soundcloud-connect-done.*
  script: soundcloud_connect_done.py

- url: /backend/soundcloud-connect/followers/
  script: backend/soundcloudconnect/network.py
  login: admin

- url: /backend/soundcloud-connect/follower/
  script: backend/soundcloudconnect/person.py
  login: admin
  
- url: /backend/soundcloud-connect/followings/
  script: backend/soundcloudconnect/network.py
  login: admin

- url: /backend/soundcloud-connect/following/
  script: backend/soundcloudconnect/person.py
  login: admin  

- url: /backend/soundcloud-connect/favorites/
  script: backend/soundcloudconnect/favorites.py
  login: admin

- url: /backend/soundcloud-connect/favorite/
  script: backend/soundcloudconnect/favorite.py
  login: admin    

- url: /api/soundcloud-connect/change-favorite/.*
  script: api/soundcloudconnect/change_favorite.py
  login: admin  

- url: /soundcloud-connect.*
  script: soundcloudconnect/main.py

- url: /from-facebook.*
  script: facebook_meta_info.py

- url: /api/.*
  script: api/main.py 

- url: /images
  static_dir: images

- url: /fonts
  static_dir: fonts

- url: /favicon.ico
  static_files: images/favicon.ico
  upload: images/favicon.ico

- url: /robots.txt
  static_files: robots.txt
  upload: robots.txt

- url: .*
  script: main.py
