application: tracksonamap
version: 1
runtime: python
api_version: 1

handlers:
- url: /scripts
  static_dir: scripts  

- url: /style
  static_dir: style  
         
- url: /backend-update/track
  script: backend_update_track.py
  login: admin

- url: /backend-update
  script: backend_update.py
  login: admin

- url: /backend-cleanup/.*
  script: backend_cleanup.py
  login: admin

- url: /backend-refill-memcache
  script: backend_refill_memcache.py
  login: admin

- url: /from-facebook.*
  script: facebook_meta_info.py

- url: /api/.*
  script: api.py 

- url: /images
  static_dir: images

- url: /fonts
  static_dir: fonts

- url: /favicon.ico
  static_files: images/favicon.ico
  upload: images/favicon.ico

- url: /robots.txt
  static_files: robots.txt
  upload: robots.txt

- url: .*
  script: main.py
